apiVersion: v1
kind: Service
metadata:
  name: devops-python-svc
  labels:
    app: devops-python
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  selector:
    app: devops-python
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP

