apiVersion: v1
kind: Service
metadata:
  name: devops-python-svc
  labels:
    app: devops-python
spec:
  selector:
    app: devops-python
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP

